# Default values for greeting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: nelvadas/greeting
  pullPolicy: IfNotPresent
  tag: 2.0.0


service:
  nodePort: 30080
  targetPort: 8080
  port: 8000
  type: NodePort

ingress:
  enabled: false
